print("Hello World !")
print("My name is Steve Martinez")
print("I like to play baseball")
var = 2018
print("Today is November the 5th", var)
print(7+13)
print(7-13)
print(7*8)
print(28/5)
print(2**3)
